Nb 146 keyboard overlaps inputs make it responsive
nebulr-group/nblocks-react-native pull request #2
Opened 2022-10-03 20:48 UTC by nemanja255

# Description

Solved the issue of iOS devices keyboard overlapping form input fields. 

# How Has This Been Tested?

- [x] Tested all of the changes on both iOS and Android devices.
- [x] Tested all occurrences of input fields and modals with the current changes. Did not manage to break design with new changes.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

# New Components

- KeyboardAvoidingComponent

# Modified Components

- NblocksModalComponent
- LoginScreen
- BrandExpoScreen

2022-10-06 08:48 UTC, orr3 requested changes
Small feedback

2022-10-06 08:48 UTC, orr3 commented on src/components/shared/KeyboardAvoidingComponent.tsx
> +        {useBehavior ? (
This block from #66 to #78 is identical with #84 to #96.
Can you put this into a separate function that can be called instead?

See how I use `renderExpanedContent` in `UserListComponent` for inspo.

2022-10-06 08:48 UTC, orr3 commented on src/screens/Auth/LoginScreen.tsx
> +      <DefaultPaddingComponent style={{ flex: 1 }}>
Is (flex: 1) required to remain on DefaultPaddingComponent now when there's a parent view (scrollview) with flex:1?

2022-10-13 08:25 UTC, nemanja255 commented on src/screens/Auth/LoginScreen.tsx
> +      <DefaultPaddingComponent style={{ flex: 1 }}>
Yeah, react native is based on flex. The nested DefaultPaddingComponent grows to fit the wrapper container which in turn grows to fit its parent... The only walk-around would be not using the DefaultPaddingComponent and set the padding on the ScrollView.

2022-10-19 08:10 UTC, merged